# Generated by Django 6.0 on 2025-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificates',
            field=models.TextField(blank=True, verbose_name='Sertifikalar'),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hasat Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='İçerik Bilgisi'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Üretim Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_location',
            field=models.CharField(default='Milas, Muğla', max_length=200, verbose_name='Üretim Yeri'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_process',
            field=models.TextField(blank=True, verbose_name='Üretim Süreci'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, verbose_name='Raf Ömrü'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, verbose_name='Saklama Koşulları'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Net Ağırlık'),
        ),
    ]
