# Generated by Django 6.0 on 2025-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_certificates_product_harvest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='', max_length=100, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, default='', verbose_name='Sipariş Notu'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
    ]
