# Generated by Django 6.0 on 2025-12-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_options_order_status_order_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Resim')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Metin')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ana Resim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ 5 Yıldız'), (4, '⭐⭐⭐⭐ 4 Yıldız'), (3, '⭐⭐⭐ 3 Yıldız'), (2, '⭐⭐ 2 Yıldız'), (1, '⭐ 1 Yıldız')], verbose_name='Puan')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylı')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Faydalı Say')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
