# Generated by Django 6.0 on 2025-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('ml', 'Mililitre (ml)'), ('l', 'Litre (l)'), ('adet', 'Adet')], default='adet', max_length=10, verbose_name='Ölçü Birimi'),
        ),
    ]
