# Generated by Django 6.0 on 2025-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_units',
            field=models.JSONField(default=list, help_text='Müşterilerin seçebileceği ölçü birimleri (kg, g, ml, l, adet)', verbose_name='Mevcut Ölçü Birimleri'),
        ),
    ]
