# Generated by Django 6.0 on 2025-12-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_available_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_amounts',
            field=models.JSONField(default=dict, help_text="Ölçü birimine göre minimum miktar (ör. {'g': 50, 'kg': 1})", verbose_name='Minimum Sipariş Miktarları'),
        ),
    ]
