# Generated by Django 6.0 on 2025-12-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_min_order_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_steps',
            field=models.JSONField(default=dict, help_text="Ölçü birimine göre sipariş artış adımı (ör. {'g': 50, 'kg': 1, 'l': 1})", verbose_name='Sipariş Artış Adımı'),
        ),
    ]
