# Generated by Django 6.0 on 2025-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_quantity_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packages',
            field=models.JSONField(blank=True, default=list, help_text="Satış paketleri: [{'size': '50g', 'price': 10.50}, {'size': '250g', 'price': 45.00}]", verbose_name='Ürün Paketleri'),
        ),
    ]
